# -*- coding: utf-8 -*-
"""Final Project_HODL_Group 17_vF

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fG5284x4504YXJR8mgqlc8lqVGlpjJh5

## **MoBu+: Deep Learning for Film Reception Prediction**

**15.773 HODL — Group 17 Final Project**

The film industry is inherently risky. Independent producers, studios, and investors must decide which projects to greenlight based on limited early-stage information — a plot synopsis, a director attachment, a lead actor, and a genre. These decisions are largely subjective and carry significant financial consequences: poor bets lead to costly failures, while promising concepts may be overlooked.

MoBu+ (Movie Budget Plus) is an AI-powered decision support tool that predicts whether a film concept is likely to be a Hit (IMDb rating ≥ 6.5) or a Flop (IMDb rating < 6.5) based on four inputs available at the concept stage: plot description, director, lead actor, and genre. The tool is trained on a dataset of approximately 60,000 films scraped from IMDb.

We approach this as a binary classification problem using deep learning. The core technical challenge is representing the free-text plot description in a way that captures meaningful narrative signals. To investigate this, we implement and compare two text representation methods:


*   Part 1 — Bag-of-Words (BoW): A sparse, word-presence-based representation that treats each plot as an unordered set of words. This serves as our baseline NLP approach.
*   Part 2 — BERT (Bidirectional Encoder Representations from Transformers): A pretrained contextual language model that produces dense semantic embeddings, capturing word order, context, and meaning.

Both models use identical architectures for the non-text inputs (genre, director, lead actor), allowing us to isolate the effect of the text representation method on prediction accuracy. We perform hyperparameter optimization over neuron count and model depth, and evaluate performance using accuracy and confusion matrices.

**Cell 1 — Environment Setup**

We begin by installing the keras-hub package, which provides access to pretrained Transformer models such as BERT.
"""

# Install keras-hub for access to pretrained Transformer models.
!pip install --upgrade keras-hub

"""**Cell 2 — Imports and Random Seed**

We import all the libraries needed for data processing, visualization, model building, and evaluation. We set the Keras backend to TensorFlow and fix the random seed to 42 so that all results are reproducible across runs.
"""

import os
os.environ['KERAS_BACKEND'] = 'tensorflow'

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import keras
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MultiLabelBinarizer
from sklearn.metrics import classification_report, confusion_matrix, ConfusionMatrixDisplay

# Fix random seed for reproducibility across all runs
keras.utils.set_random_seed(42)

"""**Cell 3 — Load the Raw Dataset**

We load the IMBD.csv file, which contains approximately 129K rows of movies and TV shows scraped from IMDb. Each row includes the title, genre, runtime, certificate, IMDb rating, cast, plot description, vote count, and director. We print the shape and null counts to understand how much cleaning will be needed.
"""

# Load the raw dataset
df = pd.read_csv('IMBD.csv')

print(f"Raw dataset: {df.shape[0]:,} rows × {df.shape[1]} columns")
print(f"\nNull counts per column:")
print(df.isnull().sum())
df.head()

"""**Cell 4 — Data Cleaning**

Several cleaning steps are necessary before we can use this data for modeling:
*   We remove rows missing any of the key fields we need: rating, description, stars (cast), director, genre, and runtime.
*   We also enforce two business-logic filters: runtime must be at least 60 minutes (to exclude TV episodes and short films) and rating must be at least 1.0 (to ensure valid IMDb scores).
*    The stars column is stored as a stringified list — we parse it to extract only the lead actor (first name listed).
*   Similarly, the director column is stored with brackets and quotes that need to be stripped.
*    Finally, we remove very short descriptions (under 20 characters) that are unlikely to represent meaningful plot summaries.

At the end we print the size of the cleaned dataset to confirm the filtering results.
"""

# Parse the lead actor from the stars column.
# The raw format is: "['Tom Cruise, ', 'Hayley Atwell, ', ...]"
# We split on comma, take the first entry, and strip brackets/quotes.
df['lead_actor'] = df['stars'].apply(
    lambda x: str(x).split(',')[0].replace('[', '').replace("'", '').strip()
    if pd.notna(x) else np.nan
)

# Parse the director name from its stringified list format.
# The raw format is: "['Christopher Nolan']"
df['director_clean'] = df['director'].apply(
    lambda x: str(x).replace('[', '').replace(']', '').replace("'", '').strip()
    if pd.notna(x) else np.nan
)

# Extract numeric runtime from strings like "131 min"
df['runtime_min'] = df['runtime'].str.extract(r'(\d+)').astype(float)

# Strip trailing whitespace from genre strings
df['genre'] = df['genre'].str.strip()

# Drop any row missing a field we need for modeling
df = df.dropna(subset=['rating', 'description', 'lead_actor', 'director_clean', 'genre', 'runtime_min'])

# Business-logic filters
df = df[df['rating'] >= 1]                    # valid IMDb scores only
df = df[df['runtime_min'] >= 60]              # films only, no TV episodes or shorts
df = df[df['description'].str.len() > 20]     # meaningful plot descriptions only

# Reset the index after all filtering
df = df.reset_index(drop=True)

print(f"Cleaned dataset: {df.shape[0]:,} rows")

df.head()

"""**Cell 5 — Define the Target Variable**

Our classification task requires converting the continuous IMDb rating into discrete categories. Based on the distribution of ratings in the dataset, we define three classes: Flop (1.0–6.4) and Hit (6.5–10.0).

We visualize both the raw rating distribution with the class boundaries marked and the resulting class counts to confirm the split produces reasonably balanced classes.
"""

# Binary classification: Flop (1.0–6.4) vs Hit (6.5–10.0)
# We set the boundary at 6.5, which sits near the median rating
# in the dataset and produces a more balanced class split.
df['label'] = (df['rating'] >= 6.5).astype(int)  # 0 = Flop, 1 = Hit

label_names = ['Flop', 'Hit']

# Print class distribution
print("Target variable distribution:")
print("-" * 40)
for i, name in enumerate(label_names):
    count = (df['label'] == i).sum()
    pct = count / len(df) * 100
    print(f"  {name:>4} (rating {'1.0–6.4' if i==0 else '6.5–10.0'}): "
          f"{count:>6,} films  ({pct:.1f}%)")
print(f"  Total: {len(df):>6,} films")

# Visualize
fig, axes = plt.subplots(1, 2, figsize=(14, 5))

axes[0].hist(df['rating'], bins=50, edgecolor='black', alpha=0.7)
axes[0].axvline(6.5, color='red', linestyle='--', label='Flop/Hit boundary (6.5)')
axes[0].set_xlabel('IMDb Rating')
axes[0].set_ylabel('Count')
axes[0].set_title('Rating Distribution with Class Boundary')
axes[0].legend()

counts = [(df['label'] == i).sum() for i in range(2)]
bars = axes[1].bar(label_names, counts, edgecolor='black', alpha=0.7,
                    color=['#e74c3c', '#2ecc71'])
for bar, count in zip(bars, counts):
    axes[1].text(bar.get_x() + bar.get_width()/2, bar.get_height() + 200,
                 f'{count:,}', ha='center', fontsize=11)
axes[1].set_ylabel('Count')
axes[1].set_title('Class Distribution: Flop vs Hit')

plt.tight_layout()
plt.show()

"""**Cell 6 — Summary Statistics: Plot Description Vocabulary**

Before deciding on a vocabulary size for the Bag-of-Words representation, we need to understand how large the actual vocabulary in our plot descriptions is. We tokenize all descriptions (lowercased, split on whitespace) and count the number of unique words. This number represents the theoretical maximum vocabulary — in practice, most of these words appear only once or twice and carry little predictive value. The BoW vectorizer's max_tokens parameter caps the vocabulary to the N most frequent words, and this analysis helps us choose a reasonable N.
"""

# Tokenize all plot descriptions and count unique words
all_words = df['description'].str.lower().str.split().explode()
total_words = len(all_words)
unique_words = all_words.nunique()

print(f"Total words across all plots: {total_words:,}")
print(f"Unique words (full vocabulary): {unique_words:,}")

# Show how word frequency is distributed
word_freq = all_words.value_counts()
print(f"\nWord frequency distribution:")
print("-" * 45)
buckets = [(1, 1), (2, 3), (4, 10), (11, 50), (51, 100), (101, 500), (501, 1000), (1001, 999999)]
for lo, hi in buckets:
    count = ((word_freq >= lo) & (word_freq <= hi)).sum()
    label = f"{lo}" if lo == hi else f"{lo}–{hi}" if hi < 999999 else f"{lo}+"
    print(f"  Appear {label:>8} times: {count:>6,} words")

# Cumulative coverage: how many of the top N words cover what % of all word occurrences
print(f"\nCumulative vocabulary coverage:")
print("-" * 45)
cumsum = word_freq.values.cumsum()
for n in [1000, 2000, 5000, 10000, 20000]:
    if n <= len(word_freq):
        pct = cumsum[n-1] / total_words * 100
        print(f"  Top {n:>6,} words cover {pct:.1f}% of all word occurrences")

print(f"\nNote: our BoW vectorizer will use max_tokens = 10000, which based on the")
print(f"above captures the vast majority of meaningful word occurrences while")
print(f"discarding the long tail of rare words that appear only once or twice.")

"""**Cell 7 — Summary Statistics: Genre**

We now examine each predictor variable to understand its characteristics. We start with genre. Since movies can belong to multiple genres simultaneously (e.g., "Action, Adventure, Drama"), we parse each genre string into a list and count how frequently each genre appears across the dataset. This confirms that all genres have sufficient representation for the model to learn from.
"""

# Parse genre strings into lists for analysis
df['genre_list'] = df['genre'].apply(lambda x: [g.strip() for g in str(x).split(',')])

# Count frequency of each individual genre across all films
all_genres = df['genre_list'].explode()
genre_freq = all_genres.value_counts()

print(f"Total unique genres: {len(genre_freq)}")
print(f"\nGenre frequency:")
print("-" * 40)
for genre, count in genre_freq.items():
    pct = count / len(df) * 100
    print(f"  {genre:<15} {count:>6,} films  ({pct:.1f}%)")

# Visualize
plt.figure(figsize=(14, 5))
genre_freq.plot(kind='bar', edgecolor='black', alpha=0.7)
plt.title('Genre Frequency Across All Films')
plt.ylabel('Number of Films')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

"""**Cell 8 — Summary Statistics: Director**

Next, we examine the director variable. With over 25,000 unique directors in the dataset, the vast majority appear in only one or two films. Encoding each director as a separate feature would create an extremely sparse, high-dimensional input that the model cannot learn from effectively. To address this, we group directors by how frequently they appear and display the distribution.

Based on this analysis, we set a minimum frequency threshold: directors who appear in fewer than 5 films are grouped into a single "Other" category. This threshold retains approximately 3,500 named directors covering about 61% of all rows, while collapsing the long tail of one-off directors into a single manageable category. The choice of 5 as the cutoff balances dimensionality reduction against information loss — lower thresholds retain too many rare names the model can't learn from, while higher thresholds discard too many recognizable directors.
"""

# === Frequency threshold — change this value to adjust the cutoff ===
MIN_DIRECTOR_FILMS = 5

# Count how many films each director has
dir_freq = df['director_clean'].value_counts()

# Build frequency distribution table
print(f"Total unique directors: {len(dir_freq):,}")
print(f"\nDirector appearance frequency:")
print("-" * 55)
buckets = [(1, 1), (2, 3), (4, 5), (6, 10), (11, 20), (21, 50), (51, 100), (101, 9999)]
for lo, hi in buckets:
    count = ((dir_freq >= lo) & (dir_freq <= hi)).sum()
    label = f"{lo}" if lo == hi else f"{lo}–{hi}" if hi < 9999 else f"{lo}+"
    print(f"  Appear in {label:>6} films: {count:>5,} directors")

# Apply the cutoff
top_directors = dir_freq[dir_freq >= MIN_DIRECTOR_FILMS].index.tolist()
df['director_final'] = df['director_clean'].apply(
    lambda x: x if x in top_directors else 'Other'
)

n_kept = len(top_directors)
pct_rows = df['director_final'].ne('Other').mean()
print(f"\nWith cutoff ≥ {MIN_DIRECTOR_FILMS} films:")
print(f"  {n_kept:,} named directors retained (+ 'Other')")
print(f"  Covering {pct_rows:.1%} of all rows")

"""**Cell 9 — Summary Statistics: Lead Actor**

We perform the same long-tail analysis for lead actors. The stars column was parsed in Cell 4 to extract only the first-billed actor. As with directors, thousands of actors appear only once, so we apply the same frequency threshold to keep the feature space manageable. Actors appearing in fewer than 5 films are grouped as "Other." This retains approximately 4,400 named actors covering about 43% of rows — a lower coverage than directors because the actor pool is more fragmented, but still sufficient for the model to learn meaningful patterns about recognizable names.
"""

# === Frequency threshold — change this value to adjust the cutoff ===
MIN_ACTOR_FILMS = 5

# Count how many films each lead actor has
actor_freq = df['lead_actor'].value_counts()

# Build frequency distribution table
print(f"Total unique lead actors: {len(actor_freq):,}")
print(f"\nLead actor appearance frequency:")
print("-" * 55)
buckets = [(1, 1), (2, 3), (4, 5), (6, 10), (11, 20), (21, 50), (51, 100), (101, 9999)]
for lo, hi in buckets:
    count = ((actor_freq >= lo) & (actor_freq <= hi)).sum()
    label = f"{lo}" if lo == hi else f"{lo}–{hi}" if hi < 9999 else f"{lo}+"
    print(f"  Appear in {label:>6} films: {count:>5,} actors")

# Apply the cutoff
top_actors = actor_freq[actor_freq >= MIN_ACTOR_FILMS].index.tolist()
df['actor_final'] = df['lead_actor'].apply(
    lambda x: x if x in top_actors else 'Other'
)

n_kept = len(top_actors)
pct_rows = df['actor_final'].ne('Other').mean()
print(f"\nWith cutoff ≥ {MIN_ACTOR_FILMS} films:")
print(f"  {n_kept:,} named actors retained (+ 'Other')")
print(f"  Covering {pct_rows:.1%} of all rows")

"""**Cell 10 — Encode Categorical Features**

Now we encode our three categorical predictor variables into numeric formats suitable for a neural network.
*   Genres are multi-hot encoded — each genre gets its own binary column, and a film can have multiple 1s simultaneously (e.g., a film that is both Action and Drama).
*   Directors and lead actors are one-hot encoded — each gets a single 1 in their respective column, since a film has exactly one director and one lead actor. The frequency cutoffs applied in Cells 8 and 9 ensure these one-hot matrices remain a manageable size.
"""

# Multi-hot encode genres: each genre becomes a binary column,
# and a movie can belong to multiple genres at once.
mlb_genre = MultiLabelBinarizer()
genre_encoded = mlb_genre.fit_transform(df['genre_list'])
print(f"Genre encoding: {genre_encoded.shape[1]} columns (genres)")

# One-hot encode directors (after applying the frequency cutoff from Cell 8)
director_dummies = pd.get_dummies(df['director_final'], prefix='dir', dtype=int)
print(f"Director encoding: {director_dummies.shape[1]} columns")

# One-hot encode lead actors (after applying the frequency cutoff from Cell 9)
actor_dummies = pd.get_dummies(df['actor_final'], prefix='act', dtype=int)
print(f"Actor encoding: {actor_dummies.shape[1]} columns")

"""**Cell 11 — Train / Test Split**

We split the data into training (80%) and test (20%) sets. Crucially, we perform this split before text vectorization to prevent data leakage — the vocabulary should be built only from training data. We split all input arrays and the target labels together so that indices remain aligned. After splitting, we compare the class distribution across the full dataset, training set, and test set to confirm that the random split did not introduce any bias.
"""

# Binary target: 0 = Flop, 1 = Hit (single column, no one-hot needed)
y = df['label'].values

# Split ALL inputs together to keep indices aligned
(plot_train, plot_test,
 genre_train, genre_test,
 dir_train, dir_test,
 actor_train, actor_test,
 y_train, y_test) = train_test_split(
    df['description'].values,
    genre_encoded,
    director_dummies.values,
    actor_dummies.values,
    y,
    test_size=0.2, random_state=42
)

print(f"Train: {len(y_train):,}   Test: {len(y_test):,}")

# Verify class distribution is preserved after splitting
fig, axes = plt.subplots(1, 3, figsize=(18, 4))
for ax, (data, title) in zip(axes, [
    (df['label'].values, 'Full Dataset'),
    (y_train, 'Training Set (80%)'),
    (y_test, 'Test Set (20%)')
]):
    counts = [np.sum(data == i) for i in range(2)]
    pcts = [c / len(data) * 100 for c in counts]
    bars = ax.bar(label_names, counts, edgecolor='black', alpha=0.7,
                  color=['#e74c3c', '#2ecc71'])
    for bar, count, pct in zip(bars, counts, pcts):
        ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 100,
                f'{count:,}\n({pct:.1f}%)', ha='center', fontsize=9)
    ax.set_title(title)
    ax.set_ylabel('Count')

plt.suptitle('Class Distribution: Full Dataset vs Train vs Test', fontsize=13, y=1.02)
plt.tight_layout()
plt.show()

"""##**Part 1 — Bag-of-Words Model**

With our data cleaned, features encoded, and train/test split verified, we now build our first model using the Bag-of-Words approach for text representation. In this method, each plot description is converted into a binary vector of length 10,000, where each position corresponds to one of the most frequent words in the training corpus.

Our BoW vector is combined with the genre, director, and lead actor branches in a multi-input neural network, and we perform a hyperparameter search to identify the best architecture before evaluating the winning model on the test set.

**Cell 12 — Text Vectorization (Bag-of-Words)**

We convert the plot descriptions into numerical vectors using Keras's TextVectorization layer. This implements a Bag-of-Words representation: each description becomes a binary vector of length max_tokens, where a 1 indicates that the corresponding word appears in the text. As we saw in Cell 6, the full vocabulary contains tens of thousands of unique words, but the top 10,000 cover the vast majority of word occurrences — the remaining words appear too rarely to carry predictive value. We use unigrams (single words), lowercase normalization, and punctuation stripping. The vocabulary is adapted on the training set only to prevent data leakage, then applied to both training and test sets.
"""

# Vocabulary size set to 10000 based on the coverage analysis in Cell 6.
# The top 10000 words capture the vast majority of word occurrences
# while discarding rare words that appear only once or twice.
max_tokens = 10000

text_vectorization = keras.layers.TextVectorization(
    max_tokens=max_tokens,
    standardize='lower_and_strip_punctuation',
    ngrams=None,          # unigrams only
    split='whitespace',
    output_mode='multi_hot'
)

# Build the vocabulary from training descriptions only (no data leakage)
text_vectorization.adapt(plot_train)

# Transform both sets into BoW vectors
X_text_train = text_vectorization(plot_train).numpy()
X_text_test  = text_vectorization(plot_test).numpy()

print(f"BoW vector shape (train): {X_text_train.shape}")
print(f"BoW vector shape (test):  {X_text_test.shape}")
print(f"Vocabulary size used:     {len(text_vectorization.get_vocabulary())}")

"""**Cell 13 — Hyperparameter Search and Final Model Selection**

We perform limited hyperparameter optimization over the model architecture. We test combinations of two hyperparameters:
1.   The number of neurons in the text branch (64, 128, or 256).
2.   The number of shared Dense layers after the merge (1 or 2).

All other parameters are held constant: vocabulary size 10000, genre/director/actor branch sizes 8 neurons* each, 20 epochs, batch size 64, dropout 0.2, and early stopping. This produces 6 combinations. Each one is trained silently and evaluated on the test set, and the results are collected into a sorted table to identify the best configuration.

Our model architecture uses separate branches for each input type — text, genre, director, and lead actor — each with a dedicated Dense layer. This allows the network to learn specialized representations before combining them via concatenation. After merging, one or two shared Dense layers learn how the combined features interact to determine whether a film is a Flop, Average, or Hit. The final layer uses softmax activation to output a probability distribution over the three classes.

Instead of discarding models after each run, we keep track of the best-performing one. Once the search is complete, the winning model is already trained and ready to use.

**NOTE: We intentionally constrain the genre, director, and actor branches to only 8 neurons to prevent the model from over-relying on categorical features like director or actor name. In early experiments with 32 neurons, the model effectively memorized "this director = Hit" lookup tables, producing near-100% confidence predictions driven almost entirely by the name rather than the plot. By limiting these branches to 8 neurons, the model cannot fully memorize name-outcome associations and is forced to rely more heavily on the plot description — which is the core NLP component of this project.*
"""

n_genres    = genre_train.shape[1]
n_directors = dir_train.shape[1]
n_actors    = actor_train.shape[1]

text_neurons_options  = [64, 128, 256]
shared_layers_options = [1, 2]

results = []
best_acc = 0
final_model = None
final_history = None

print("Running hyperparameter search (6 combinations)...")
print("-" * 55)

for text_neurons in text_neurons_options:
    for n_shared in shared_layers_options:

        t_in = keras.layers.Input(shape=(max_tokens,), name='text')
        t_x  = keras.layers.Dense(text_neurons, activation='relu')(t_in)

        g_in = keras.layers.Input(shape=(n_genres,), name='genre')
        g_x  = keras.layers.Dense(8, activation='relu')(g_in)

        d_in = keras.layers.Input(shape=(n_directors,), name='director')
        d_x  = keras.layers.Dense(8, activation='relu')(d_in)

        a_in = keras.layers.Input(shape=(n_actors,), name='actor')
        a_x  = keras.layers.Dense(8, activation='relu')(a_in)

        m = keras.layers.Concatenate()([t_x, g_x, d_x, a_x])
        x = keras.layers.Dense(64, activation='relu')(m)
        x = keras.layers.Dropout(0.2)(x)
        if n_shared == 2:
            x = keras.layers.Dense(32, activation='relu')(x)
            x = keras.layers.Dropout(0.2)(x)

        out = keras.layers.Dense(1, activation='sigmoid')(x)

        hp_model = keras.Model(inputs=[t_in, g_in, d_in, a_in], outputs=out)
        hp_model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

        hp_history = hp_model.fit(
            [X_text_train, genre_train, dir_train, actor_train], y_train,
            epochs=20, batch_size=64, validation_split=0.15,
            verbose=0
        )

        _, acc = hp_model.evaluate(
            [X_text_test, genre_test, dir_test, actor_test], y_test, verbose=0
        )

        results.append((text_neurons, n_shared, acc))
        print(f"  neurons={text_neurons}, shared_layers={n_shared}  →  accuracy: {acc:.2%}")

        # Keep the best model instead of deleting it
        if acc > best_acc:
            best_acc = acc
            final_model = hp_model
            final_history = hp_history
        else:
            del hp_model
            keras.backend.clear_session()

# Display sorted results
results_df = pd.DataFrame(results, columns=['Text Neurons', 'Shared Layers', 'Test Accuracy'])
results_df = results_df.sort_values('Test Accuracy', ascending=False).reset_index(drop=True)
print("\n" + "=" * 55)
print("HYPERPARAMETER SEARCH RESULTS")
print("=" * 55)
print(results_df.to_string(index=False))

best_neurons = int(results_df.iloc[0]['Text Neurons'])
best_shared  = int(results_df.iloc[0]['Shared Layers'])
print(f"\nBest: neurons={best_neurons}, shared_layers={best_shared}")
print(f"Test Accuracy: {best_acc:.2%}")
print(f"\nFinal model is already trained and ready to use.")

final_model.summary()

"""**Cell 14 — Final Model: Training Curves**

We plot the loss and accuracy curves for the final model across training epochs. The gap between the training and validation lines indicates how much the model is overfitting — if training accuracy climbs much higher than validation accuracy, the model is memorizing training data rather than learning generalizable patterns. Ideally, both lines converge and flatten, showing stable learning.
"""

fig, axes = plt.subplots(1, 2, figsize=(14, 5))

# Loss curve
axes[0].plot(final_history.history['loss'], label='Train')
axes[0].plot(final_history.history['val_loss'], label='Validation')
axes[0].set_title('Final Model — Loss (Categorical Crossentropy)')
axes[0].set_xlabel('Epoch'); axes[0].set_ylabel('Loss'); axes[0].legend()

# Accuracy curve
axes[1].plot(final_history.history['accuracy'], label='Train')
axes[1].plot(final_history.history['val_accuracy'], label='Validation')
axes[1].set_title('Final Model — Accuracy')
axes[1].set_xlabel('Epoch'); axes[1].set_ylabel('Accuracy'); axes[1].legend()

plt.tight_layout()
plt.show()

"""**Cell 15 — Final Model: Classification Report and Confusion Matrix**

Beyond overall accuracy, we evaluate per-class performance. Precision measures what fraction of films predicted as a given class actually belonged to that class. Recall measures what fraction of actual members of a class were correctly identified. F1-score is the harmonic mean of the two, providing a single balanced metric. The confusion matrix shows the full breakdown of predictions versus actual labels, making it easy to identify systematic errors — for example, whether the model tends to confuse Average films with Hits, which would be expected given the narrow boundary between those classes.
"""

# Generate predictions on the test set
y_pred_probs = final_model.predict([X_text_test, genre_test, dir_test, actor_test]).flatten()
y_pred = (y_pred_probs >= 0.5).astype(int)  # threshold at 0.5
y_true = y_test

print("Classification Report (Final Model):")
print("=" * 55)
print(classification_report(y_true, y_pred, target_names=label_names))

cm = confusion_matrix(y_true, y_pred)
disp = ConfusionMatrixDisplay(cm, display_labels=label_names)
fig, ax = plt.subplots(figsize=(6, 5))
disp.plot(cmap='Blues', ax=ax)
plt.title('Confusion Matrix (Final Model)')
plt.show()

"""## **PART 2: Transitioning to BERT: Why Bag-of-Words Falls Short**
Our BoW model achieved 70.18% accuracy — a meaningful improvement over the 57% baseline (i.e., always predicting the majority class), but far from perfect. The core limitation is that Bag-of-Words treats every plot description as an unordered set of words, discarding all contextual information. For example, the phrases "a hero saves the world" and "the world saves a hero" produce identical BoW vectors despite having opposite meanings.

BERT addresses this directly. As a pretrained contextual language model, BERT reads the entire sentence at once and understands how words relate to each other. It produces a single 768-dimensional embedding for each plot description that captures the meaning of the text — not just which words appear, but how they interact. This richer representation should help the model better distinguish between plot descriptions that lead to Hits versus Flops.

Importantly, we keep everything else identical — the genre, director, and actor branches remain unchanged. The only thing that changes is how the plot text is represented: a sparse 10000-dimensional BoW vector is replaced by a dense 768-dimensional BERT embedding. This isolates the effect of the text representation and gives us a clean comparison between the two approaches.

**Cell 16 — Kaggle Credentials and BERT Imports**

BERT model weights are hosted on Kaggle through the Keras Hub repository. We load our Kaggle credentials from Colab's Secrets manager and import the keras_hub library, which provides a convenient interface for downloading and using pretrained models.
"""

# Load Kaggle credentials from Colab Secrets.
# These are needed to download BERT weights from Keras Hub.
# Set them up in Colab: click the key icon in the left sidebar,
# then add KAGGLE_USERNAME and KAGGLE_KEY.
from google.colab import userdata
os.environ["KAGGLE_USERNAME"] = userdata.get('KAGGLE_USERNAME')
os.environ["KAGGLE_KEY"]      = userdata.get('KAGGLE_KEY')

import keras_hub

"""**Cell 17 — Load Pretrained BERT**

We load bert_base_en_uncased, a pretrained BERT model with 109 million parameters trained on a massive English text corpus. We only use the backbone — the encoder portion that converts text into embeddings. The classification head on top (specified by num_classes and activation) is a placeholder required by the API but never used in our pipeline. Think of it as buying a car for the engine: we pull out the encoder and discard the rest.

"""

# Load the pretrained BERT model from Keras Hub.
# We only use bert.backbone (the encoder) and bert.preprocessor (the tokenizer).
# The classification head (num_classes, activation) is a required placeholder
# that we never use — our own MLP handles the classification.
bert = keras_hub.models.BertClassifier.from_preset(
    "bert_base_en_uncased",
    activation="softmax",
    num_classes=6   # placeholder — ignored in our pipeline
)

# Inspect the backbone architecture
print("BERT Backbone:")
bert.backbone.summary()

"""**Cell 18 — Free Memory Before BERT Extraction**

Before running the BERT extraction, we free as much memory as possible. The BoW text matrices (X_text_train and X_text_test) are large and no longer needed — the BoW final model and its results are already saved. We keep the BoW model itself (for the comparison later) but clear everything else we can.
"""

import gc
import tensorflow as tf

# Delete the large BoW text matrices — no longer needed
del X_text_train, X_text_test
gc.collect()
tf.keras.backend.clear_session()

print("Memory freed. Ready for BERT extraction.")

"""**Cell 19 — Extract BERT Embeddings**

We pass every plot description through BERT's backbone and extract the CLS token embedding — a 768-dimensional vector at position 0 of the output sequence that serves as a summary representation of the entire input text. Unlike BoW, this vector captures the contextual meaning of the plot, not just which words appear.
We process texts in small batches (32 at a time) to avoid running out of GPU memory, and explicitly free memory after each batch.
"""

import gc
import tensorflow as tf

BATCH_SIZE = 32

def get_bert_embeddings(texts, batch_size=BATCH_SIZE):
    """
    Extract CLS token embeddings from BERT backbone in batches.
    Each text is tokenized by BERT's preprocessor, passed through the
    backbone encoder, and the first token's output (the CLS token)
    is kept as the 768-dim representation of the entire text.
    """
    all_emb = []
    n = len(texts)
    for i in range(0, n, batch_size):
        batch = texts[i:i+batch_size]
        # Tokenize the batch using BERT's built-in preprocessor
        tok = bert.preprocessor(batch)
        # Run through the backbone and extract the CLS token (position 0)
        emb = bert.backbone.predict(tok, verbose=0)['sequence_output'][:, 0, :]
        all_emb.append(emb)
        # Free memory after each batch to prevent OOM
        del tok, emb
        if (i // batch_size) % 100 == 0:
            print(f"  {min(i+batch_size, n):,} / {n:,}")
    return np.concatenate(all_emb, axis=0)

# Extract embeddings for training and test sets
print("Extracting BERT embeddings for training set...")
X_bert_train = get_bert_embeddings(list(plot_train))
print(f"  shape: {X_bert_train.shape}")

print("Extracting BERT embeddings for test set...")
X_bert_test = get_bert_embeddings(list(plot_test))
print(f"  shape: {X_bert_test.shape}")

# Save to disk so we never have to run this again
np.save('bert_train_emb.npy', X_bert_train)
np.save('bert_test_emb.npy',  X_bert_test)
print("Embeddings saved to disk.")

"""**Cell 20 — Hyperparameter Search (BERT)**

We run the same hyperparameter search as the BoW model — testing text branch neuron counts (64, 128, 256) and shared layer counts (1, 2) — but now the text branch input is a 768-dimensional BERT embedding instead of a 10000-dimensional BoW vector. All other branches (genre, director, actor) remain exactly the same. This ensures a fair comparison: the only difference between the BoW and BERT pipelines is how the plot text is represented.

As before, we keep the best-performing model directly from the search rather than retraining it.
"""

# The BERT embedding dimension replaces max_tokens as the text input size
bert_dim = X_bert_train.shape[1]  # 768

text_neurons_options  = [64, 128, 256]
shared_layers_options = [1, 2]

bert_results = []
bert_best_acc = 0
bert_final_model = None
bert_final_history = None

print("Running BERT hyperparameter search (6 combinations)...")
print("-" * 55)

for text_neurons in text_neurons_options:
    for n_shared in shared_layers_options:

        # --- Text branch: now takes 768-dim BERT embeddings instead of BoW ---
        t_in = keras.layers.Input(shape=(bert_dim,), name='text')
        t_x  = keras.layers.Dense(text_neurons, activation='relu')(t_in)

        # --- Genre, director, actor branches: identical to BoW model ---
        g_in = keras.layers.Input(shape=(n_genres,), name='genre')
        g_x  = keras.layers.Dense(8, activation='relu')(g_in)

        d_in = keras.layers.Input(shape=(n_directors,), name='director')
        d_x  = keras.layers.Dense(8, activation='relu')(d_in)

        a_in = keras.layers.Input(shape=(n_actors,), name='actor')
        a_x  = keras.layers.Dense(8, activation='relu')(a_in)

        # Merge all branches
        m = keras.layers.Concatenate()([t_x, g_x, d_x, a_x])

        # Shared classification layers
        x = keras.layers.Dense(64, activation='relu')(m)
        x = keras.layers.Dropout(0.2)(x)
        if n_shared == 2:
            x = keras.layers.Dense(32, activation='relu')(x)
            x = keras.layers.Dropout(0.2)(x)

        # Binary output: sigmoid for Flop vs Hit
        out = keras.layers.Dense(1, activation='sigmoid')(x)

        hp_model = keras.Model(inputs=[t_in, g_in, d_in, a_in], outputs=out)
        hp_model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

        # Train — note X_bert_train replaces X_text_train as the text input
        hp_history = hp_model.fit(
            [X_bert_train, genre_train, dir_train, actor_train], y_train,
            epochs=20, batch_size=64, validation_split=0.15,
            verbose=0
        )

        _, acc = hp_model.evaluate(
            [X_bert_test, genre_test, dir_test, actor_test], y_test, verbose=0
        )

        bert_results.append((text_neurons, n_shared, acc))
        print(f"  neurons={text_neurons}, shared_layers={n_shared}  →  accuracy: {acc:.2%}")

        # Keep the best model instead of deleting it
        if acc > bert_best_acc:
            bert_best_acc = acc
            bert_final_model = hp_model
            bert_final_history = hp_history
        else:
            del hp_model
            keras.backend.clear_session()

# Display sorted results
bert_results_df = pd.DataFrame(bert_results, columns=['Text Neurons', 'Shared Layers', 'Test Accuracy'])
bert_results_df = bert_results_df.sort_values('Test Accuracy', ascending=False).reset_index(drop=True)
print("\n" + "=" * 55)
print("BERT HYPERPARAMETER SEARCH RESULTS")
print("=" * 55)
print(bert_results_df.to_string(index=False))

bert_best_neurons = int(bert_results_df.iloc[0]['Text Neurons'])
bert_best_shared  = int(bert_results_df.iloc[0]['Shared Layers'])
print(f"\nBest: neurons={bert_best_neurons}, shared_layers={bert_best_shared}")
print(f"Test Accuracy: {bert_best_acc:.2%}")
print(f"\nBERT final model is already trained and ready to use.")

bert_final_model.summary()

"""**Cell 21 — BERT Model: Training Curves**

We plot the training curves for the best BERT model. Comparing these to the BoW training curves from Cell 14 can reveal differences in learning dynamics — for example, whether BERT converges faster or achieves lower validation loss, which would indicate it is extracting more useful information from the plot descriptions.
"""

fig, axes = plt.subplots(1, 2, figsize=(14, 5))

# Loss curve
axes[0].plot(bert_final_history.history['loss'], label='Train')
axes[0].plot(bert_final_history.history['val_loss'], label='Validation')
axes[0].set_title('BERT Model — Loss (Binary Crossentropy)')
axes[0].set_xlabel('Epoch'); axes[0].set_ylabel('Loss'); axes[0].legend()

# Accuracy curve
axes[1].plot(bert_final_history.history['accuracy'], label='Train')
axes[1].plot(bert_final_history.history['val_accuracy'], label='Validation')
axes[1].set_title('BERT Model — Accuracy')
axes[1].set_xlabel('Epoch'); axes[1].set_ylabel('Accuracy'); axes[1].legend()

plt.tight_layout()
plt.show()

"""**Cell 22 — BERT Model: Classification Report and Confusion Matrix**

We evaluate the BERT model using the same metrics as the BoW model — precision, recall, F1-score, and the confusion matrix. This allows a direct comparison: if BERT improves recall on Hits without sacrificing precision on Flops (or vice versa), it confirms that the contextual embeddings are providing a richer text representation.
"""

# Generate predictions on the test set
bert_pred_probs = bert_final_model.predict(
    [X_bert_test, genre_test, dir_test, actor_test]
).flatten()
bert_pred = (bert_pred_probs >= 0.5).astype(int)  # threshold at 0.5
y_true = y_test

# Per-class precision, recall, F1-score
print("Classification Report (BERT Model):")
print("=" * 55)
print(classification_report(y_true, bert_pred, target_names=label_names))

# Confusion matrix
cm = confusion_matrix(y_true, bert_pred)
disp = ConfusionMatrixDisplay(cm, display_labels=label_names)
fig, ax = plt.subplots(figsize=(6, 5))
disp.plot(cmap='Blues', ax=ax)
plt.title('Confusion Matrix (BERT Model)')
plt.show()

"""**Cell 23 — Side-by-Side Comparison: BoW vs BERT**

Finally, we compare the two approaches directly. This is the key result of the project: by holding everything constant except the text representation method, we can measure exactly how much value contextual embeddings add over a simple bag-of-words approach for predicting film reception.
"""

# Pull the BoW accuracy from Cell 13 and BERT accuracy from Cell 20
print("=" * 55)
print("MODEL COMPARISON: BoW vs BERT")
print("=" * 55)
print(f"  BoW  best accuracy: {best_acc:.2%}")
print(f"  BERT best accuracy: {bert_best_acc:.2%}")
print(f"  Improvement:        {bert_best_acc - best_acc:+.2%}")
print()

# Side-by-side confusion matrices
fig, axes = plt.subplots(1, 2, figsize=(13, 5))

# BoW confusion matrix — reuse predictions from Cell 15 (y_pred)
# y_pred was computed before we deleted X_text_test
cm_bow = confusion_matrix(y_test, y_pred)
ConfusionMatrixDisplay(cm_bow, display_labels=label_names).plot(cmap='Oranges', ax=axes[0])
axes[0].set_title(f'BoW Model\nAccuracy: {best_acc:.2%}')

# BERT confusion matrix
cm_bert = confusion_matrix(y_test, bert_pred)
ConfusionMatrixDisplay(cm_bert, display_labels=label_names).plot(cmap='Blues', ax=axes[1])
axes[1].set_title(f'BERT Model\nAccuracy: {bert_best_acc:.2%}')

plt.tight_layout()
plt.show()

"""**Cell 24 — MoBu+ Prediction Function**

This is the core deliverable of the project: a function that takes a new movie concept — plot description, director, lead actor, and genres — and predicts whether it is likely to be a Flop or Hit. The function encodes each input using the same preprocessing pipelines built during BERT training (BERT embedding for plot text, multi-hot for genres, one-hot for director and actor), then passes them through the final model. It outputs the predicted class along with the probability assigned to each category, displayed as a visual bar.
"""

def mobu_predict_bert(plot, director, lead_actor, genres):
    """
    MoBu+ Decision Support Tool (BERT version).

    Given a movie concept, predicts whether it will be a Flop or Hit
    using BERT contextual embeddings for the plot description.
    """

    # Embed the plot using the BERT backbone already in memory
    tok = bert.preprocessor([plot])
    text_emb = bert.backbone.predict(tok, verbose=0)['sequence_output'][:, 0, :]

    # Multi-hot encode the genre list
    genre_vec = mlb_genre.transform([genres])

    # One-hot encode the director (map to 'Other' if below frequency cutoff)
    dir_clean = director if director in top_directors else 'Other'
    dir_vec = np.zeros((1, director_dummies.shape[1]))
    col_name = f'dir_{dir_clean}'
    if col_name in director_dummies.columns:
        dir_vec[0, director_dummies.columns.get_loc(col_name)] = 1

    # One-hot encode the lead actor (map to 'Other' if below frequency cutoff)
    act_clean = lead_actor if lead_actor in top_actors else 'Other'
    act_vec = np.zeros((1, actor_dummies.shape[1]))
    col_name = f'act_{act_clean}'
    if col_name in actor_dummies.columns:
        act_vec[0, actor_dummies.columns.get_loc(col_name)] = 1

    # Run the BERT model
    hit_prob = bert_final_model.predict(
        [text_emb, genre_vec, dir_vec, act_vec], verbose=0
    ).flatten()[0]
    flop_prob = 1 - hit_prob
    pred_class = 1 if hit_prob >= 0.5 else 0

    # Display results
    print("=" * 65)
    print("  MoBu+ PREDICTION REPORT (BERT)")
    print("=" * 65)
    print(f"  Plot:     {plot[:80]}...")
    print(f"  Director: {director}")
    print(f"  Lead:     {lead_actor}")
    print(f"  Genres:   {', '.join(genres)}")
    print()
    print(f"  >>> Prediction: {label_names[pred_class]} <<<")
    print()
    print(f"  Probabilities:")
    flop_bar = '█' * int(flop_prob * 30)
    hit_bar  = '█' * int(hit_prob * 30)
    print(f"    Flop: {flop_prob:5.1%}  {flop_bar}")
    print(f"     Hit: {hit_prob:5.1%}  {hit_bar}")
    print("=" * 65)

"""**Cell 25 — BERT Test Predictions**

We test the prediction function with six diverse movie concepts to verify it produces sensible results. The first is a big-budget sci-fi blockbuster with a well-known director and rising star — we would expect a "Hit" prediction. The second is a low-budget horror film with unknown talent — likely a "Flop". The third is a prestige drama with an acclaimed director and A-list actor — another likely "Hit." The fourth is the actual plot of Star Wars: A New Hope (IMDb 8.6) — a known Hit — serving as a ground-truth sanity check. The fifth and sixth are quite average proposals, expected to generate a closer "Hit" vs "Flop" probability.
"""

# Test 1: Big-budget sci-fi blockbuster
mobu_predict_bert(
    plot="In a distant galaxy ruled by a ruthless interstellar empire, a young "
         "mechanic from a forgotten desert planet discovers a mysterious power. "
         "When a rebel alliance recruits the young hero, they must leave home "
         "and join a daring mission to steal the empire's ultimate weapon plans.",
    director="Christopher Nolan",
    lead_actor="Timothée Chalamet",
    genres=['Sci-Fi', 'Adventure', 'Action']
)

# Test 2: Low-budget horror with unknown talent
mobu_predict_bert(
    plot="A group of college students rent a remote cabin for spring break. "
         "Strange noises begin at night. One by one they disappear into the "
         "surrounding woods, hunted by something ancient and hungry.",
    director="Unknown Director",
    lead_actor="Unknown Actor",
    genres=['Horror', 'Thriller']
)

# Test 3: Prestige drama with A-list talent
mobu_predict_bert(
    plot="A brilliant but troubled mathematician struggles with addiction "
         "while trying to prove a theorem that could change the field forever. "
         "Along the way, a patient mentor helps him confront his past and "
         "find meaning beyond his work.",
    director="Martin Scorsese",
    lead_actor="Leonardo DiCaprio",
    genres=['Drama', 'Biography']
)

# Test 4: Star Wars — known ground truth (IMDb 8.6, should predict Hit)
mobu_predict_bert(
    plot="Luke Skywalker joins forces with a Jedi Knight, a cocky pilot, a Wookiee "
         "and two droids to save the galaxy from the Empire's world-destroying battle "
         "station, while also attempting to rescue Princess Leia from the mysterious "
         "Darth Vader.",
    director="George Lucas",
    lead_actor="Mark Hamill",
    genres=['Action', 'Adventure']
)

# Test 5: Thoroughly average movie — familiar but unremarkable
mobu_predict_bert(
    plot="A recently divorced father moves to a new city to start over. "
         "He struggles to balance a demanding office job with raising his "
         "two kids on weekends. When he meets a kind neighbor, he slowly "
         "learns to open up again.",
    director="Peter Segal",
    lead_actor="Gerard Butler",
    genres=['Comedy']
)

# Test 6: Forgettable romantic drama
mobu_predict_bert(
    plot="A woman returns to her small hometown after years in the city "
         "for her mother's funeral. She reconnects with her high school "
         "sweetheart and must decide between her career in New York and "
         "the simpler life she left behind.",
    director="Garry Marshall",
    lead_actor="Katherine Heigl",
    genres=['Drama', 'Romance']
)